package io.devportal.state;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import com.fasterxml.jackson.dataformat.yaml.YAMLGenerator;
import io.devportal.asset.Asset;
import io.devportal.asset.AssetRepository;
import io.devportal.asset.Dependency;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
@EnableConfigurationProperties(StateProperties.class)
public class StateService {

    private static final Logger log = LoggerFactory.getLogger(StateService.class);

    private final StateProperties properties;
    private final AssetRepository assets;
    private final ObjectMapper yaml;

    public StateService(StateProperties properties, AssetRepository assets) {
        this.properties = properties;
        this.assets = assets;
        this.yaml = new ObjectMapper(
            new YAMLFactory()
                .disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)
                .enable(YAMLGenerator.Feature.MINIMIZE_QUOTES))
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
            .findAndRegisterModules();
    }

    public Path stateDir() {
        return Path.of(properties.repo());
    }

    /** Snapshot the DB into a tree of YAML files under {@link #stateDir()}. Returns the dir. */
    @Transactional(readOnly = true)
    public Path export() throws IOException {
        Path root = stateDir();
        Path assetsDir = root.resolve("assets");
        Files.createDirectories(assetsDir);

        List<Asset> all = assets.findAll(null, null, null);
        for (Asset a : all) {
            List<Dependency> deps = assets.findDependenciesOf(a.id());
            Map<String, Object> doc = assetToDoc(a, deps);
            Path file = assetsDir.resolve(a.id() + ".yaml");
            yaml.writeValue(file.toFile(), doc);
        }

        // README and a stable index file so the repo is self-describing.
        Files.writeString(root.resolve("README.md"),
            "# devportal-state\n\nGenerated by dev_portal export. Do not edit by hand.\n");

        Map<String, Object> index = new LinkedHashMap<>();
        index.put("schemaVersion", 1);
        index.put("assetCount", all.size());
        index.put("assetIds", all.stream().map(Asset::id).toList());
        yaml.writeValue(root.resolve("index.yaml").toFile(), index);

        log.info("Exported {} assets to {}", all.size(), root);
        return root;
    }

    /** Reads the tree and replaces DB state. Destructive — clears existing assets first. */
    @Transactional
    public ImportResult importTree() throws IOException {
        Path root = stateDir();
        Path assetsDir = root.resolve("assets");
        if (!Files.isDirectory(assetsDir)) {
            throw new IOException("State dir missing or has no assets/: " + assetsDir);
        }

        // Pass 1: load all asset definitions, insert nodes.
        List<Map<String, Object>> docs = new ArrayList<>();
        try (Stream<Path> files = Files.list(assetsDir)) {
            files.filter(p -> p.toString().endsWith(".yaml"))
                .sorted()
                .forEach(p -> docs.add(readDoc(p)));
        }

        // Wipe in dependency-safe order: dependency rows then assets cascade.
        for (Asset a : assets.findAll(null, null, null)) {
            assets.delete(a.id());
        }

        for (Map<String, Object> doc : docs) {
            Asset a = docToAsset(doc);
            assets.insert(a);
        }

        // Pass 2: now that all assets exist, install dependency edges.
        int edges = 0;
        for (Map<String, Object> doc : docs) {
            String consumer = (String) doc.get("id");
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> deps = (List<Map<String, Object>>) doc.getOrDefault("dependencies", List.of());
            for (Map<String, Object> d : deps) {
                assets.insertDependency(
                    consumer,
                    (String) d.get("producerId"),
                    (String) d.getOrDefault("versionRef", "main"),
                    (String) d.getOrDefault("kind", "build"));
                edges++;
            }
        }

        log.info("Imported {} assets and {} dependency edges from {}", docs.size(), edges, root);
        return new ImportResult(docs.size(), edges);
    }

    private Map<String, Object> assetToDoc(Asset a, List<Dependency> deps) {
        Map<String, Object> doc = new LinkedHashMap<>();
        doc.put("id", a.id());
        doc.put("name", a.name());
        if (a.description() != null) doc.put("description", a.description());
        if (a.owner() != null) doc.put("owner", a.owner());
        doc.put("type", a.type());
        if (a.language() != null) doc.put("language", a.language());
        doc.put("repoUrl", a.repoUrl());
        doc.put("repoDefaultBranch", a.repoDefaultBranch());
        if (a.tags() != null && !a.tags().isEmpty()) doc.put("tags", a.tags());
        doc.put("lifecycle", a.lifecycle());
        if (a.favorite()) doc.put("favorite", true);
        if (a.rating() != null) doc.put("rating", a.rating());
        if (!deps.isEmpty()) {
            List<Map<String, Object>> depDocs = new ArrayList<>();
            for (Dependency d : deps) {
                Map<String, Object> dd = new LinkedHashMap<>();
                dd.put("producerId", d.producerId());
                dd.put("versionRef", d.versionRef());
                dd.put("kind", d.kind());
                depDocs.add(dd);
            }
            doc.put("dependencies", depDocs);
        }
        return doc;
    }

    private Asset docToAsset(Map<String, Object> doc) {
        @SuppressWarnings("unchecked")
        List<String> tags = (List<String>) doc.getOrDefault("tags", List.of());
        Object ratingObj = doc.get("rating");
        Integer rating = (ratingObj instanceof Number n) ? n.intValue() : null;
        boolean favorite = Boolean.TRUE.equals(doc.get("favorite"));
        return new Asset(
            (String) doc.get("id"),
            (String) doc.get("name"),
            (String) doc.get("description"),
            (String) doc.get("owner"),
            (String) doc.get("type"),
            (String) doc.get("language"),
            (String) doc.get("repoUrl"),
            (String) doc.getOrDefault("repoDefaultBranch", "main"),
            tags,
            (String) doc.getOrDefault("lifecycle", "experimental"),
            (String) doc.get("k8sNamespace"),
            favorite, rating,
            Boolean.TRUE.equals(doc.get("dashboardPinned")),
            null, null
        );
    }


    private Map<String, Object> readDoc(Path file) {
        try {
            @SuppressWarnings("unchecked")
            Map<String, Object> m = yaml.readValue(file.toFile(), Map.class);
            return m;
        } catch (IOException e) {
            throw new RuntimeException("Failed reading " + file, e);
        }
    }

    public record ImportResult(int assets, int edges) {}
}
