package io.devportal.runtime.k8s.scaffold;

import io.devportal.asset.Asset;
import io.devportal.manifest.Manifest;
import io.devportal.port.PortSlotInferrer;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * Scaffolds a {@code Dockerfile} for an asset that doesn't have one. Right now it knows about:
 * <ul>
 *   <li>Maven Spring Boot apps — uses a multi-stage build with a Java JRE runtime</li>
 *   <li>Gradle Java apps (Kotlin or Groovy DSL) — same pattern, runs {@code ./gradlew bootJar}</li>
 *   <li>Generic shell repos — minimal alpine + entrypoint placeholder</li>
 * </ul>
 *
 * <p>Java version is read from {@code <maven.compiler.target>} or {@code java.toolchain.languageVersion}
 * when present, falling back to 21.
 */
@Component
public class DockerfileScaffolder {

    private static final Logger log = LoggerFactory.getLogger(DockerfileScaffolder.class);

    private static final Pattern MVN_JAVA_VERSION = Pattern.compile(
        "<maven\\.compiler\\.target>\\s*(\\d+)\\s*</maven\\.compiler\\.target>");
    private static final Pattern MVN_JAVA_SOURCE = Pattern.compile(
        "<maven\\.compiler\\.source>\\s*(\\d+)\\s*</maven\\.compiler\\.source>");
    private static final Pattern GRADLE_JAVA_VERSION = Pattern.compile(
        "JavaLanguageVersion\\.of\\(\\s*(\\d+)\\s*\\)");

    private final PortSlotInferrer ports;

    public DockerfileScaffolder(PortSlotInferrer ports) {
        this.ports = ports;
    }

    public Result scaffold(Asset asset, Path workspace) throws IOException {
        Path dockerfile = workspace.resolve("Dockerfile");
        if (Files.exists(dockerfile)) {
            return new Result(false, "Dockerfile already exists; not overwriting");
        }

        Stack stack = detectStack(workspace);
        int javaVersion = detectJavaVersion(workspace, stack);
        List<Manifest.Port> slots = ports.infer(workspace);
        int httpPort = slots.stream()
            .filter(s -> "http".equals(s.name()))
            .findFirst()
            .map(s -> 8080)  // inferrer doesn't carry the original port number; pick the convention
            .orElse(8080);

        String content = switch (stack) {
            case MAVEN_JAVA -> mavenSpringBootDockerfile(javaVersion, httpPort);
            case GRADLE_JAVA -> gradleSpringBootDockerfile(javaVersion, httpPort);
            case NODE -> nodeDockerfile(httpPort);
            case SHELL -> shellDockerfile(httpPort);
        };

        Files.writeString(dockerfile, content);
        log.info("Scaffolded Dockerfile for {} (stack={}, java={}, port={})",
            asset.id(), stack, javaVersion, httpPort);
        return new Result(true, "Wrote " + dockerfile.getFileName());
    }

    private Stack detectStack(Path ws) {
        if (Files.exists(ws.resolve("pom.xml"))) return Stack.MAVEN_JAVA;
        if (Files.exists(ws.resolve("build.gradle.kts")) || Files.exists(ws.resolve("build.gradle"))) {
            return Stack.GRADLE_JAVA;
        }
        if (Files.exists(ws.resolve("package.json"))) return Stack.NODE;
        return Stack.SHELL;
    }

    private int detectJavaVersion(Path ws, Stack stack) {
        try {
            if (stack == Stack.MAVEN_JAVA) {
                String pom = Files.readString(ws.resolve("pom.xml"));
                Matcher m = MVN_JAVA_VERSION.matcher(pom);
                if (m.find()) return Integer.parseInt(m.group(1));
                m = MVN_JAVA_SOURCE.matcher(pom);
                if (m.find()) return Integer.parseInt(m.group(1));
            } else if (stack == Stack.GRADLE_JAVA) {
                Path b = Files.exists(ws.resolve("build.gradle.kts"))
                    ? ws.resolve("build.gradle.kts") : ws.resolve("build.gradle");
                String text = Files.readString(b);
                Matcher m = GRADLE_JAVA_VERSION.matcher(text);
                if (m.find()) return Integer.parseInt(m.group(1));
            }
        } catch (IOException ignored) {}
        return 21;
    }

    private String mavenSpringBootDockerfile(int javaVersion, int port) {
        // Thin (single-stage) Dockerfile. Multi-stage breaks for assets that depend on other
        // portal-managed Maven artifacts because a clean build container can't reach the host's
        // ~/.m2. The portal's deep-build flow populates ~/.m2 + target/, then this image just
        // packages the resulting jar.
        return """
            # Generated by dev_portal — thin runtime image.
            # Run `mvn -DskipTests package` (or kick a portal deep build) before `docker build .`.
            FROM eclipse-temurin:%d-jre
            WORKDIR /app
            ARG JAR_FILE=target/*.jar
            COPY ${JAR_FILE} /app/app.jar
            EXPOSE %d
            ENV JAVA_OPTS=""
            ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /app/app.jar"]
            """.formatted(javaVersion, port);
    }

    private String gradleSpringBootDockerfile(int javaVersion, int port) {
        return """
            # Generated by dev_portal — thin runtime image.
            # Run `./gradlew bootJar -x test` (or kick a portal deep build) before `docker build .`.
            FROM eclipse-temurin:%d-jre
            WORKDIR /app
            COPY build/libs/*.jar /app/app.jar
            EXPOSE %d
            ENV JAVA_OPTS=""
            ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /app/app.jar"]
            """.formatted(javaVersion, port);
    }

    private String nodeDockerfile(int port) {
        return """
            FROM node:20-alpine
            WORKDIR /app
            COPY package*.json pnpm-lock.yaml* ./
            RUN if [ -f pnpm-lock.yaml ]; then npm install -g pnpm && pnpm install --frozen-lockfile; \\
                else npm ci; fi
            COPY . .
            EXPOSE %d
            CMD ["node", "."]
            """.formatted(port);
    }

    private String shellDockerfile(int port) {
        return """
            FROM alpine:3.20
            WORKDIR /app
            COPY . .
            EXPOSE %d
            CMD ["/bin/sh", "-c", "echo 'configure CMD for this asset'"]
            """.formatted(port);
    }

    public enum Stack { MAVEN_JAVA, GRADLE_JAVA, NODE, SHELL }
    public record Result(boolean wrote, String message) {}
}
